version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_test
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
    volumes:
      - ./data/minio-persistence:/data
      - ./data/minio-persistence/certs:/certs
    ports:
      - '9004:9004'
    command: server /export --address ":9004"
    dns:
      - "127.0.0.11"
      - "8.8.8.8"

  filestorage:
    image: spring-boot-minio-ex:latest
    container_name: spring-boot-minio-ex
    environment:
      PROJECT_PROFILES: "dev" #dev,prod
      MINIO_URL: http://minio:9004
      MINIO_BUCKET: "file-storage"
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MAX_FILE_SIZE: "20MB"
      MAX_REQUEST_SIZE: "20MB"
      FILE-SIZE-THRESHOLD: "2KB"
    ports:
      - '8075:8075'
