version: '3.7'

services:

  minio:
    image: minio/minio:RELEASE.2018-09-01T00-38-25Z
    ports:
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /export --address ":9002"
    dns:
      - "127.0.0.11"
      - "8.8.8.8"

  nginx:
    image: nginx:1.14.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf:ro
    dns:
      - "127.0.0.11"
      - "8.8.8.8"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "digital_library"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres